### ISSUE TITLE
[generation] prolongate map

### ISSUE THREAD

**Issue by Intey** [Intey/Fogue#1]
Идея сгенерировать мир по существующей карте.  Пример:

``` Python
"0#.........#.....###..#0"
"2####......#.....##...#8"
"2#..#.....##.....###..#8"
"2#........#...........#8"
"2#..#####.#......##..##8"
"3#......###......######9"
```

Для такой карты могло бы быть сгенерированно продолжение сверху:

``` Python
"2##.......#.#...##....#9"
"0#.........#.....###..#0"
"2####......#.....##...#8"
"2#..#.....##.....###..#8"
"2#........#...........#8"
"2#..#####.#......##..##8"
```

Идея в том, что определяется состояние комнаты на текущий момент. Если верхняя линия - не является "серединой объема" - продолжить расширение(учитывая относительность соседних комнат), если же это середина или за ней - продолжить сужать комнату.

**Comment by alicedead** [comment]
Посмотри на генерацию карты в оригинальной [Rogue](http://en.wikipedia.org/wiki/Rogue_%28video_game%29). Там комнаты разбавлены коридорами. Так будет проще дорисовывать карту.

Ещё: карта двигается _(как в DF)_ или остаётся на месте? Если не двигать карту, тогда можно будет не париться по поводу генерирования продолжения.

**Comment by Intey** [comment]
оу. Я думал карта - лес и ущелья. Вот типо этого 
![2015-03-02-201931_644x436_scrot](https://cloud.githubusercontent.com/assets/3807133/6446086/74d4e0a6-c100-11e4-8076-ed79273d8280.png)

**Comment by Intey** [comment]
> Ещё: карта двигается (как в DF) или остаётся на месте? Если не двигать карту, тогда можно будет не париться по поводу генерирования продолжения.

Я бы хотел заморочиться над генерацией продолжения движущейся карты, ибо в этом одна из фич. Если не двигать, то генерация становится типичной. И с чем остаемся? В чем фича? ТО что по сейву можно изменить весь мир? Без нормального интерфейса это будет прикалывать первые пару раз, потом тупо окажется неудобным открывать сейв, менять, сохранять. Если не закрыл - прога упадет на следующем же шаге. 
ИМХО идея изменять сейв заманчива, но ей нужен интерфейс тогда уж. А-ля hot-key и ты в режиме редактирования мира. Как vim. Иначе я например взбешусь после второго раза, когда забуду закрыть сейв.

**Comment by alicedead** [comment]
Да, было бы неплохо. А как насчёт вообще без продолжения карты? То есть только то, что есть на экране? Меньше проблем.

**Comment by alicedead** [comment]
Ох, об одном и том же.

**Comment by alicedead** [comment]
За нас уже написали - `vim`, `nano`, etc... :)

**Comment by alicedead** [comment]
> И с чем остаемся? В чем фича?

_В написании первого рогалика_

**Comment by alicedead** [comment]
Второй раз нажимаю на эту кнопу..

**Comment by Intey** [comment]
Предлагаешь сначала все вообще сделать минимально? Комнаты, коридоры. Но все своими руками?

**Comment by alicedead** [comment]
Вроде того. Сразу многое прояснится. А позже наращивать.

**Comment by Intey** [comment]
Тогда закрываем задачку, как не актуальную.
